 
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.8.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

      steps:
      - checkout
      - run: npm install

      
      